version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-front
    ports:
      - "5000:5000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile-back
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  redis:
    image: redis
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped
