version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-front
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

  backend:
    build:
      context: .
      dockerfile: Dockerfile-back
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
