version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-front
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

  backend:
    build:
      context: .
      dockerfile: Dockerfile-back
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
